config/routes.rb
Rails.application.routes.draw do
  authenticated :user, -> (user) { user.admin? } do
    mount Delayed::Web::Engine, at: '/jobs'
  end
  root 'pages#home'
  devise_for :users, controllers: { registrations: 'registrations' }
  get 'dashboard', to: 'pages#dashboard'
  resources :posts do
    member do
      patch :cancel
    end
  end

  get 'auth/:provider/callback', to: 'connections#create'
  get 'auth/failure', to: 'connections#omniauth_failure'
  resources :connections, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/connection.rb
class Connection < ApplicationRecord
  belongs_to :user

  def self.create_from_omniauth(auth_hash)
    create(provider: auth_hash.provider, oauth_token: auth_hash.credentials.token, secret: auth_hash.credentials.secret)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates_presence_of :content
  validates_presence_of :scheduled_at
  validates_length_of :content, maximum: 140, message: 'Less then 140 characters please'
  validates_datetime :scheduled_at, on: :create, on_or_after: Time.zone.now
  after_create :schedule

  scope :scheduled, -> { where(state: 'scheduled').order('scheduled_at ASC') }
  scope :history,   -> { where.not(state: 'scheduled').order('scheduled_at DESC') }

  def to_twitter
    client = Twitter::REST::Client.new do |config|
      config.access_token = user.twitter.oauth_token
      config.access_token_secret = user.twitter.secret
      config.consumer_key = ENV['TWITTER_KEY']
      config.consumer_secret = ENV['TWITTER_SECRET']
    end
    client.update(content)
  end

  def to_facebook
    user_graph = Koala::Facebook::API.new(user.facebook.oauth_token)
    user_graph.put_connections('me', 'feed', message: content)
  end

  def to_facebook_page(name = 'Judo Klub Tuzla')
    user_graph = Koala::Facebook::API.new(user.facebook.oauth_token)
    pages = user_graph.get_connections('me', 'accounts')
    fb_page = pages.select { |page| page['name'] == name }
    page_access_token = fb_page[0]['access_token']
    page_graph = Koala::Facebook::API.new(page_access_token)
    page_graph.put_connections('me', 'feed', message: content)
  end

  def display
    return unless state == 'canceled'
    to_twitter if twitter
    to_facebook if facebook
    to_facebook_page if facebook_page
    update_attributes(state: 'posted')
  rescue StandardError => e
    update_attributes(state: 'posting error', error: e.message)
  end

  def schedule
    SchedulePostsJob.set(wait_until: scheduled_at).perform_later(self)
    update_attributes(state: 'scheduled')
  rescue StandardError => e
    update_attributes(state: 'scheduled error', error: e.message)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :time_zone
  has_many :connections, dependent: :destroy
  has_many :posts, dependent: :destroy

  def facebook
    connections.where(provider: 'facebook').first
  end

  def twitter
    connections.where(provider: 'twitter').first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  around_action :user_time_zone, if: :current_user

  private

  def user_time_zone(&block)
    Time.use_zone current_user.time_zone, &block
  end
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
  before_action :set_connection, only: :destroy
  def create
    connection = current_user.connections.create_from_omniauth(auth_hash)

    if connection.save
      redirect_to dashboard_path, notice: 'Connection created'
    else
      redirect_to dashboard_path, notice: 'Something went wrong!'
    end
  end

  def destroy
    redirect_to dashboard_path, notice: 'Connection terminated!' if @connection.destroy
  end

  def omniauth_failure
    redirect_to dashboard_path, notice: 'Authentication failed! Something went wrong.'
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end

  def set_connection
    @connection = Connection.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: :dashboard

  def home
    redirect_to dashboard_path if current_user
  end

  def dashboard
    @scheduled = current_user.posts.scheduled.paginate(page: params[:scheduled_page], per_page: 4)
    @history = current_user.posts.history.paginate(page: params[:history_page], per_page: 4)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: :cancel

  def new
    if current_user.connections.any?
      @post = Post.new
    else
      redirect_to dashboard_path, notice: 'Please create connection first!'
    end
  end

  def create
    @post = current_user.posts.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to dashboard_path, notice: 'Post successfully created!' }
      else
        format.html { render :new }
      end
    end
  end

  def cancel
    @post.update_attributes(state: 'canceled')
    redirect_to dashboard_path, notice: 'Post successfully canceled'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:content, :scheduled_at, :state, :user_id, :facebook, :twitter, :facebook_page)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def update
    if resource.update_with_password(account_params)
      flash[:success] = 'Account updated!'
      redirect_to edit_user_registration_path
    else
      render :edit
    end
  end

  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :time_zone)
  end

  def account_params
    params.require(:user).permit(:email, :password, :current_password, :time_zone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/connections_helper.rb
module ConnectionsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li>
          <%= value %>
        </li>
      </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Soci-Poster", root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to 'New post', new_post_path %></li>
          <li><%= link_to 'Dashboard', dashboard_path %></li>
          <li><%= link_to 'Edit', edit_user_registration_path %></li>
          <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SociPoster</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/header' %>

    <div class="container">

    <%= render 'layouts/flash_messages' %>

      <%= yield %>

    </div>

  </body>
</html>

app/views/pages/_provider.html.erb
<% unless current_user.connections.where(provider: "#{provider}").any? %>
  <%= link_to "Connect #{provider.capitalize}", "auth/#{provider}", class: "btn btn-#{provider_class} btn-block btn-sm" %>
<% else %>
  <%= link_to "Connect #{provider.capitalize}", "auth/#{provider}", class: "btn btn-#{provider_class} btn-block btn-sm", disabled: true %>
  <%= link_to 'Disconnect', connection_path(current_user.connections.where(provider: "#{provider}").first), method: :delete %>
<% end %>

app/views/pages/dashboard.html.erb
<div class="row">

  <div class="col-md-2 text-center">
    <%= image_tag 'soci_poster.svg', class: 'logo' %>
    <hr>

    <div class="time-zone">
      <p class="text-center">
        <b><%= Time.zone.name %> Timezone </b>
        <%= link_to 'change', edit_user_registration_path %>
      </p>
    </div>

    <div class="social">
      <%= render partial: 'provider', locals: { provider: 'twitter', provider_class: 'info'} %>
      <%= render partial: 'provider', locals: { provider: 'facebook', provider_class: 'primary'} %>
    </div>
  </div>

  <div class="col-md-5">
    <h3 class="text-center">Scheduled</h3>
    <hr>
    <%= render @scheduled %>
    <%= will_paginate @scheduled, :param_name => 'scheduled_page' %>
  </div>

  <div class="col-md-5">
    <h3 class="text-center">History</h3>
    <hr>
    <%= render @history %>
    <%= will_paginate @history, :param_name => 'scheduled_page' %>
  </div>

</div>

app/views/pages/home.html.erb
<h1>Welcome to Soci-Poster</h1>
<div class="text-center landing_title">
  <%= link_to "The freedom to post", new_user_session_path, class:'btn btn-default btn-lg btn-landing' %>
</div>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f|  %>
  <%= f.error_notification %>
  <div class="form-input">
    <%= f.input :content, required: true, maxlength: 140 %>
    <p>This post will be scheduled in <b><%= Time.zone.name %></b></p>
    <%= f.input :scheduled_at, required: true, as: :datetime_picker %>
  </div>
  <div class="form-input">
    <% if current_user.connections.where(provider: 'twitter').any? %>
      <%= f.input :twitter %>
    <% end %>
    <% if current_user.connections.where(provider: 'facebook').any? %>
      <%= f.input :facebook %>
      <%= f.input :facebook_page %>
    <% end %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="panel panel-default">
  <!-- heading -->
  <div class="panel-heading">
    <% if post.facebook == true %> <span class="label label-primary"></span> <% end %>
    <% if post.twitter == true %> <span class="label label-info"></span> <% end %>
    Scheduled on <%= post.scheduled_at %>
  </div>
  <!-- body -->
  <div class="panel-body">
    <%= post.content %>
  </div>
  <div class="panel-footer">
    <p><%= post.state.capitalize %> <%= link_to 'cancel post', cancel_post_path(post), method: :patch if post.state == 'scheduled' %> </p>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>
<%= link_to "back", dashboard_path %>